import { RefreshCw } from 'lucide-react'
import { Skeleton } from './Skeleton'

const SECTION_NAMES = ['Root Cause', 'Error Pattern', 'Immediate Fix', 'Prevention'] as const

function parseSections(summary: string): Partial<Record<(typeof SECTION_NAMES)[number], string>> {
  const pattern = new RegExp(
    `\\*\\*(${SECTION_NAMES.join('|')})\\*\\*:?\\s*([\\s\\S]*?)(?=\\*\\*(?:${SECTION_NAMES.join('|')})\\*\\*|$)`,
    'g',
  )
  const sections: Partial<Record<(typeof SECTION_NAMES)[number], string>> = {}
  let match: RegExpExecArray | null
  while ((match = pattern.exec(summary))) {
    const name = match[1] as (typeof SECTION_NAMES)[number]
    sections[name] = match[2].trim()
  }
  return sections
}

function toBullets(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.replace(/^[-•*]\s*/, '').trim())
    .filter(Boolean)
}

function AnthropicMark({ size = 12 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="none">
      <path
        d="M8 2 L14 14 H10.5 L8 9 L5.5 14 H2 Z"
        fill="var(--text-secondary)"
      />
    </svg>
  )
}

function isFallbackText(summary: string): boolean {
  return !summary.includes('**Root Cause**')
}

interface AiSummaryCardProps {
  summary: string | null
  isGenerating: boolean
  onReanalyze?: () => void
  reanalyzing?: boolean
}

export function AiSummaryCard({ summary, isGenerating, onReanalyze, reanalyzing }: AiSummaryCardProps) {
  return (
    <div className="rounded-lg border border-border bg-card p-5">
      <div className="mb-4 flex items-center justify-between">
        <div className="flex items-center gap-2 text-sm font-medium" style={{ color: 'var(--accent)' }}>
          <span>⬡</span>
          AI Root Cause Analysis
        </div>
        {onReanalyze && (
          <button
            type="button"
            onClick={onReanalyze}
            disabled={reanalyzing || isGenerating}
            aria-label="Reanalyze"
            className="rounded-md p-1.5 text-secondary transition-colors hover:bg-elevated hover:text-primary disabled:opacity-50"
          >
            <RefreshCw size={14} className={reanalyzing ? 'animate-spin' : ''} />
          </button>
        )}
      </div>

      {summary === null || isGenerating ? (
        <div>
          <Skeleton rows={3} />
          <div className="mt-3 text-xs text-secondary">Analyzing failure pattern...</div>
        </div>
      ) : isFallbackText(summary) ? (
        <div className="text-sm italic text-secondary">{summary}</div>
      ) : (
        <ReadySummary summary={summary} />
      )}
    </div>
  )
}

function ReadySummary({ summary }: { summary: string }) {
  const sections = parseSections(summary)

  return (
    <div className="space-y-4">
      {sections['Root Cause'] && (
        <div>
          <div className="text-sm font-semibold text-primary">Root Cause</div>
          <div className="mt-1 text-[0.95rem] leading-relaxed text-primary">
            {sections['Root Cause']}
          </div>
        </div>
      )}

      {sections['Error Pattern'] && (
        <div>
          <span
            className="inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium"
            style={{ backgroundColor: 'var(--accent-glow)', color: 'var(--accent)' }}
          >
            {sections['Error Pattern']}
          </span>
        </div>
      )}

      {sections['Immediate Fix'] && (
        <div>
          <div className="text-xs uppercase tracking-wide text-secondary">Immediate Fix</div>
          <ul className="mt-1.5 space-y-1">
            {toBullets(sections['Immediate Fix']).map((bullet, i) => (
              <li key={i} className="flex gap-2 text-sm text-primary">
                <span style={{ color: 'var(--accent)' }}>●</span>
                <span>{bullet}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {sections['Prevention'] && (
        <div>
          <div className="text-xs uppercase tracking-wide text-secondary">Prevention</div>
          <ul className="mt-1.5 space-y-1">
            {toBullets(sections['Prevention']).map((bullet, i) => (
              <li key={i} className="flex gap-2 text-sm text-primary">
                <span style={{ color: 'var(--success)' }}>●</span>
                <span>{bullet}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="flex items-center justify-end gap-1.5 border-t border-border pt-3 text-xs text-secondary">
        <AnthropicMark />
        Generated by Claude
      </div>
    </div>
  )
}
