"""add_job_max_delay_seconds

Revision ID: 4fc2ad3f8218
Revises: eb64a4b530ce
Create Date: 2026-07-05 03:34:54.503871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc2ad3f8218'
down_revision: Union[str, None] = 'eb64a4b530ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('max_delay_seconds', sa.Integer(), server_default=sa.text('3600'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_delay_seconds')
    # ### end Alembic commands ###
