"""cascade_delete_on_job_and_dlq_fks

Revision ID: ac0b8fb9e6ce
Revises: 100cb347e2b7
Create Date: 2026-07-05 22:17:19.014117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0b8fb9e6ce'
down_revision: Union[str, None] = '100cb347e2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dead_letter_queue_entries_job_id_fkey', 'dead_letter_queue_entries', type_='foreignkey')
    op.create_foreign_key(None, 'dead_letter_queue_entries', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('jobs_queue_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'queues', ['queue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_queue_id_fkey', 'jobs', 'queues', ['queue_id'], ['id'])
    op.drop_constraint(None, 'dead_letter_queue_entries', type_='foreignkey')
    op.create_foreign_key('dead_letter_queue_entries_job_id_fkey', 'dead_letter_queue_entries', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
